// __mocks__/cacheStrategy.js
module.exports = {
  getOrSet: jest.fn((key, fn) => fn()),
  invalidate: jest.fn(),
  KEYS: {
    userProfile: (userId) => `user:profile:${userId}`,
    userKyc: (userId) => `user:kyc:${userId}`,
    userWallet: (userId) => `user:wallet:${userId}`,
    marketListings: (filters) => `market:listings:${JSON.stringify(filters)}`,
    marketStats: () => 'market:stats',
    priceEthInr: () => 'price:eth:inr',
    priceToken: (tokenId) => `price:token:${tokenId}`,
    carbonBatches: (userId) => `carbon:batches:${userId}`,
    carbonListings: (params) => `carbon:listings:${JSON.stringify(params)}`,
    carbonStats: () => 'carbon:stats',
    walletBalance: (userId) => `wallet:balance:${userId}`,
    walletTransactions: (userId, params) => `wallet:tx:${userId}:${JSON.stringify(params)}`,
    subscriptionStatus: (userId) => `sub:status:${userId}`,
    subscriptionPrices: () => 'sub:prices',
    buyOrders: (params) => `market:buyorders:${JSON.stringify(params)}`,
    emissionsSummary: (userId, year) => `emissions:summary:${userId}:${year}`,
    emissionActivities: (userId, params) => `emissions:activities:${userId}:${JSON.stringify(params)}`,
    portfolioCredits: (userId, limit, cursor) => `portfolio:credits:${userId}:${limit}:${cursor || 'first'}`,
    portfolioBought: (userId) => `portfolio:bought:${userId}`,
    brsrData: (userId, year) => `brsr:${userId}:${year}`,
    brsrSection: (userId, year, section) => `brsr:${userId}:${year}:${section}`,
    kycStatus: (userId) => `kyc:status:${userId}`,
    adminStats: () => 'admin:stats',
    adminDashboard: () => 'admin:dashboard',
    erpSyncStatus: (orgId, erpId) => `erp:sync:${orgId}:${erpId}`,
    erpData: (orgId, erpId) => `erp:data:${orgId}:${erpId}`,
  },
};