import { tableSchema } from '@nozbe/watermelondb';

// User model
export const userSchema = tableSchema({
  name: 'users',
  columns: [
    { name: 'email', type: 'string', isIndexed: true },
    { name: 'full_name', type: 'string' },
    { name: 'company_name', type: 'string' },
    { name: 'role', type: 'string' },
    { name: 'kyc_status', type: 'string' },
    { name: 'subscription_plan', type: 'string' },
    { name: 'wallet_address', type: 'string', isIndexed: true },
    { name: 'inr_balance', type: 'number' },
    { name: 'subscription_renewal_date', type: 'number' },
    { name: 'org_id', type: 'string' },
    { name: 'is_company_account', type: 'boolean' },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
  ],
});

// Emission Activity model
export const emissionActivitySchema = tableSchema({
  name: 'emission_activities',
  columns: [
    { name: 'user_id', type: 'string', isIndexed: true },
    { name: 'org_id', type: 'string', isIndexed: true },
    { name: 'date', type: 'number', isIndexed: true },
    { name: 'activity', type: 'string' },
    { name: 'quantity', type: 'number' },
    { name: 'unit', type: 'string' },
    { name: 'scope', type: 'number' },
    { name: 'category', type: 'string' },
    { name: 'factor', type: 'number' },
    { name: 'co2e', type: 'number' },
    { name: 'notes', type: 'string' },
    { name: 'source', type: 'string' },
    { name: 'verified', type: 'boolean' },
    { name: 'ai_audit', type: 'string' },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
    { name: 'logged_at', type: 'number' },
    { name: 'approval_state', type: 'string' },
  ],
});

// Carbon Asset model
export const carbonAssetSchema = tableSchema({
  name: 'carbon_assets',
  columns: [
    { name: 'asset_id', type: 'string', isIndexed: true },
    { name: 'token_id', type: 'number' },
    { name: 'project_id', type: 'string' },
    { name: 'registry', type: 'string' },
    { name: 'vintage', type: 'number' },
    { name: 'methodology', type: 'string' },
    { name: 'serial_number', type: 'string' },
    { name: 'total_supply', type: 'number' },
    { name: 'retired_supply', type: 'number' },
    { name: 'status', type: 'string' },
    { name: 'project_name', type: 'string' },
    { name: 'standard', type: 'string' },
    { name: 'project_type', type: 'string' },
    { name: 'geography', type: 'string' },
    { name: 'ecs_score', type: 'number' },
    { name: 'ecs_grade', type: 'string' },
    { name: 'ecs_percentile', type: 'number' },
    { name: 'last_traded_price', type: 'number' },
    { name: 'available_quantity', type: 'number' },
    { name: 'compliance_eligible', type: 'boolean' },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
  ],
});

// MRV Plan model
export const mrvPlanSchema = tableSchema({
  name: 'mrv_plans',
  columns: [
    { name: 'plan_id', type: 'string', isIndexed: true },
    { name: 'user_id', type: 'string', isIndexed: true },
    { name: 'org_id', type: 'string', isIndexed: true },
    { name: 'plan_name', type: 'string' },
    { name: 'description', type: 'string' },
    { name: 'reporting_year', type: 'number' },
    { name: 'methodology_template', type: 'string' },
    { name: 'covers_scope_1', type: 'boolean' },
    { name: 'covers_scope_2', type: 'boolean' },
    { name: 'covers_scope_3', type: 'boolean' },
    { name: 'facility_ids', type: 'string', isIndexed: true },
    { name: 'asset_ids', type: 'string', isIndexed: true },
    { name: 'reporting_period_start', type: 'number', isIndexed: true },
    { name: 'reporting_period_end', type: 'number', isIndexed: true },
    { name: 'submission_deadline', type: 'number' },
    { name: 'verification_deadline', type: 'number' },
    { name: 'state', type: 'string' },
    { name: 'previous_state', type: 'string' },
    { name: 'submitted_at', type: 'number' },
    { name: 'verified_at', type: 'number' },
    { name: 'approved_at', type: 'number' },
    { name: 'rejected_at', type: 'number' },
    { name: 'rejection_reason', type: 'string' },
    { name: 'submitted_by', type: 'string' },
    { name: 'verified_by', type: 'string' },
    { name: 'approved_by', type: 'string' },
    { name: 'assigned_verifier', type: 'string' },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
  ],
});

// Evidence model
export const evidenceSchema = tableSchema({
  name: 'evidence',
  columns: [
    { name: 'evidence_id', type: 'string', isIndexed: true },
    { name: 'plan_id', type: 'string', isIndexed: true },
    { name: 'activity_id', type: 'string', isIndexed: true },
    { name: 'title', type: 'string' },
    { name: 'description', type: 'string' },
    { name: 'evidence_type', type: 'string' },
    { name: 'ipfs_cid', type: 'string' },
    { name: 'ipfs_gateway_url', type: 'string' },
    { name: 'file_name', type: 'string' },
    { name: 'file_size', type: 'number' },
    { name: 'mime_type', type: 'string' },
    { name: 'file_hash_sha256', type: 'string' },
    { name: 'blockchain_tx_hash', type: 'string' },
    { name: 'blockchain_log_index', type: 'number' },
    { name: 'anchored_at', type: 'number' },
    { name: 'state', type: 'string' },
    { name: 'uploaded_by', type: 'string' },
    { name: 'uploaded_at', type: 'number' },
    { name: 'verified_by', type: 'string' },
    { name: 'verified_at', type: 'number' },
    { name: 'verification_notes', type: 'string' },
    { name: 'ai_extracted_data', type: 'string' },
    { name: 'extraction_confidence', type: 'number' },
    { name: 'source_file_name', type: 'string' },
    { name: 'was_edited', type: 'boolean' },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
  ],
});

// Trade model
export const tradeSchema = tableSchema({
  name: 'trades',
  columns: [
    { name: 'trade_id', type: 'string', isIndexed: true },
    { name: 'buyer_id', type: 'string', isIndexed: true },
    { name: 'seller_id', type: 'string', isIndexed: true },
    { name: 'asset_id', type: 'string', isIndexed: true },
    { name: 'quantity', type: 'number' },
    { name: 'price_per_credit_inr', type: 'number' },
    { name: 'subtotal_inr', type: 'number' },
    { name: 'buyer_fee_inr', type: 'number' },
    { name: 'seller_fee_inr', type: 'number' },
    { name: 'total_fee_inr', type: 'number' },
    { name: 'gst_inr', type: 'number' },
    { name: 'buyer_pays_inr', type: 'number' },
    { name: 'seller_receives_inr', type: 'number' },
    { name: 'platform_net_inr', type: 'number' },
    { name: 'price_per_credit_eth', type: 'number' },
    { name: 'total_eth', type: 'number' },
    { name: 'eth_inr_rate', type: 'number' },
    { name: 'fee_eth', type: 'number' },
    { name: 'payment_mode', type: 'string' },
    { name: 'status', type: 'string' },
    { name: 'tx_hash', type: 'string' },
    { name: 'razorpay_payment_id', type: 'string' },
    { name: 'razorpay_order_id', type: 'string' },
    { name: 'buyer_inr_deducted', type: 'boolean' },
    { name: 'seller_inr_credited', type: 'boolean' },
    { name: 'inr_settlement_at', type: 'number' },
    { name: 'completed_at', type: 'number' },
    { name: 'idempotency_key', type: 'string' },
    { name: 'chain_status', type: 'string' },
    { name: 'chain_tx_hash', type: 'string' },
    { name: 'chain_block', type: 'number' },
    { name: 'chain_logged_at', type: 'number' },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
  ],
});

export const allSchemas = [
  userSchema,
  emissionActivitySchema,
  carbonAssetSchema,
  mrvPlanSchema,
  evidenceSchema,
  tradeSchema,
];