// ─────────────────────────────────────────────────────────────────────────────
// knowledgeBase.js — EtherTrack Support Knowledge Base
// VERSION: Production Final
// ─────────────────────────────────────────────────────────────────────────────
//
// STRUCTURE:
//   KNOWLEDGE_BASE  — 14 modules (app features + glossary + FAQ + edge cases)
//   INTENT_PATTERNS — intent detection for chat engine
//   BOT_PERSONA     — Ethi's name, greeting, fallback messages
//
// HOW TO ADD A NEW MODULE:
//   1. Add a new object to KNOWLEDGE_BASE array before the closing ];
//   2. Each subtopic supports:
//      - question    : what the user is asking
//      - keywords    : words/phrases to match (more = better search)
//      - answer      : short conversational reply (1–2 sentences)
//      - steps       : optional step-by-step array
//      - followUps   : chips shown after answer (must be exact questions in KB or natural phrases)
//      - escalate    : true → always show ticket CTA after answer
//      - tags        : for intent boosting — see tag list below
//
// INTENT TAGS:
//   "error" "billing" "account" "blocked" "kyc" "wallet" "inr"
//   "market" "portfolio" "dashboard" "glossary" "edge-case"
// ─────────────────────────────────────────────────────────────────────────────

export const KNOWLEDGE_BASE = [

  // ── MODULE 1: Getting Started ──────────────────────────────────────────────
  {
    id: "getting-started",
    icon: "🚀",
    label: "Getting Started",
    subtopics: [
      {
        id: "what-is-ethertrack",
        question: "What is EtherTrack?",
        keywords: ["what is", "ethertrack", "about", "platform", "overview", "intro", "explain"],
        answer: "EtherTrack is a blockchain-powered platform for carbon credit trading and emissions tracking. Organizations use it to log GHG emissions, buy/sell/retire carbon credits, achieve regulatory compliance, and generate on-chain verified certificates.",
        followUps: ["how do i get started", "how do i sign up", "what plans does ethertrack offer"],
        tags: [],
      },
      {
        id: "how-to-signup",
        question: "How do I sign up?",
        keywords: ["sign up", "signup", "register", "create account", "new user", "get started", "join"],
        answer: "Signing up takes less than 2 minutes! Here's how:",
        steps: [
          "Go to the EtherTrack homepage and click 'Sign Up' (or GET STARTED in the top-right header)",
          "Choose your method — Email/Password, Google, or Facebook",
          "If using Email: enter your full name, email, and a password of 8+ characters (needs uppercase, number, special character)",
          "Click 'Create Account' — a 6-digit OTP is emailed to you (expires in 10 minutes)",
          "Enter the OTP and click 'Verify & Sign In' — you are taken to the Dashboard automatically",
          "If using Google/Facebook: click the social button, complete the popup, and you're in immediately",
          "Complete KYC verification (required for trading features)",
          "Join or create your organization",
          "Select a plan — you can start with the Free tier",
        ],
        followUps: ["i didn't receive my verification otp / email", "what is kyc and why do i need it", "how do i join an existing organization"],
        tags: ["account"],
      },
      {
        id: "signup-otp",
        question: "I didn't receive my verification OTP / email",
        keywords: ["otp", "verification code", "didn't receive email", "no email", "resend otp", "otp expired", "verification email", "otp not received"],
        answer: "No worries — here's how to get your OTP:",
        steps: [
          "Check your spam or promotions folder first",
          "Wait 60 seconds — the Resend timer must count down before you can request again",
          "Click 'Resend code' on the OTP screen to get a fresh code",
          "Make sure you typed the correct email address — click 'Back to sign up' to check",
          "The OTP expires in 10 minutes — request a fresh one if it expired",
          "If you still don't receive it after retrying, contact support@ethertrack.in",
        ],
        followUps: ["i'm getting an error during sign up", "i can't log in to my account"],
        tags: ["account", "error"],
      },
      {
        id: "signup-errors",
        question: "I'm getting an error during sign up",
        keywords: ["signup error", "signup failed", "account already exists", "passwords do not match", "invalid email", "create account error", "error signing up"],
        answer: "Here are the most common signup errors and how to fix them:",
        steps: [
          "'Account already exists. Please log in.' — your email is already registered. Go to Login and use Forgot Password if needed.",
          "'Invalid email format.' — check that your email has @ and a valid domain.",
          "'Password must be at least 8 characters.' — use a longer password.",
          "'Passwords do not match.' — re-type your password carefully. Note: paste is disabled in the Confirm Password field.",
          "'Signup failed. Please try again.' — server or network error. Wait a moment and retry.",
          "If issues persist, try a different browser or incognito mode.",
        ],
        followUps: ["i can't log in to my account", "i didn't receive my verification otp / email"],
        tags: ["account", "error"],
      },
      {
        id: "login-issues",
        question: "I can't log in to my account",
        keywords: ["cant login", "can't login", "login failed", "login error", "wrong password", "forgot password", "not logging in", "access denied", "unable to login"],
        answer: "Let's get you back in. Here are the most common fixes:",
        steps: [
          "Make sure you're using the correct email address",
          "Try 'Forgot Password' on the login page — type your email FIRST, then click the link",
          "If you signed up with Google/Facebook, use that same login button — not email/password",
          "Clear your browser cache and cookies, then try again",
          "Try a different browser or incognito mode",
          "If you see 'Too many attempts. Reset your password.' — use Forgot Password immediately",
          "If your account is disabled, email support@ethertrack.in",
        ],
        followUps: ["what do login error messages mean", "i see a 'session expired' message"],
        tags: ["error", "account", "blocked"],
        escalate: true,
      },
      {
        id: "login-errors",
        question: "What do login error messages mean?",
        keywords: ["login error message", "incorrect email or password", "account disabled", "email not verified", "social login error", "login message"],
        answer: "Here's what each login error means and how to fix it:",
        steps: [
          "'Incorrect email or password.' — credentials don't match. Double-check and retry.",
          "'This account was created with Google or Facebook.' — click the social login button instead.",
          "'Email not verified. Check your inbox for the 6-digit code.' — sign up again to resend your OTP.",
          "'This account has been disabled. Contact support.' — email support@ethertrack.in.",
          "'Too many attempts. Reset your password.' — too many failed logins. Use Forgot Password.",
        ],
        followUps: ["i can't log in to my account", "i didn't receive my verification otp / email"],
        tags: ["account", "error"],
      },
      {
        id: "session-expired",
        question: "I see a 'Session Expired' message",
        keywords: ["session expired", "logged out automatically", "session timeout", "kicked out", "log in again", "session ended"],
        answer: "Sessions expire automatically for security. When this happens, a fullscreen modal appears saying 'Your session has expired'. Simply click 'LOG IN AGAIN' to be taken to the Login page — your data is all safe.",
        followUps: ["i can't log in to my account"],
        tags: ["account"],
      },
    ],
  },

  // ── MODULE 2: KYC Verification ────────────────────────────────────────────
  {
    id: "kyc",
    icon: "🪪",
    label: "KYC Verification",
    subtopics: [
      {
        id: "what-is-kyc",
        question: "What is KYC and why do I need it?",
        keywords: ["kyc", "what is kyc", "why kyc", "identity", "verification", "why verify", "kyc needed"],
        answer: "KYC (Know Your Customer) is a one-time identity verification required to trade carbon credits, access your wallet, and use advanced features. It keeps the platform secure and compliant with DPDP Act 2023, IT Act 2000, and UIDAI guidelines.",
        followUps: ["how do i complete kyc", "what documents are accepted for kyc", "how long does kyc approval take"],
        tags: ["kyc"],
      },
      {
        id: "how-to-complete-kyc",
        question: "How do I complete KYC?",
        keywords: ["complete kyc", "submit kyc", "kyc form", "how to kyc", "kyc process", "kyc steps", "do kyc", "kyc verification steps"],
        answer: "KYC has 4 steps and takes under 5 minutes. Here's the full process:",
        steps: [
          "Step 1 — Identity Details: Go to KYC section (or click VERIFY NOW on dashboard). Enter your full legal name, select ID type, and enter your ID number. Your actual ID number is never stored — only a cryptographic hash.",
          "Step 2 — Upload Document: Upload a clear photo of your government ID (JPG, PNG, or PDF, max 5MB). A preview appears after upload. Document is stored securely on IPFS.",
          "Step 3 — Verify Phone: Enter your 10-digit Indian mobile number. Click 'Send OTP', enter the 6-digit SMS code within 60 seconds, and click 'Verify OTP'.",
          "Step 4 — Review & Submit: Review all your details. Aadhaar is masked to last 4 digits. Click 'Submit For Review'.",
          "After submission: you'll see an 'Under Review' screen. Wait 1–2 business days for approval — you'll get an email notification.",
        ],
        followUps: ["what documents are accepted for kyc", "how long does kyc approval take", "my kyc was rejected. what do i do"],
        tags: ["kyc"],
      },
      {
        id: "kyc-documents",
        question: "What documents are accepted for KYC?",
        keywords: ["kyc documents", "accepted documents", "what documents", "id proof", "aadhaar", "pan", "passport", "driving license", "voter id", "kyc id"],
        answer: "EtherTrack accepts the following government-issued IDs:",
        steps: [
          "Aadhaar Card — spaces stripped automatically",
          "PAN Card — auto-converted to uppercase",
          "Passport (bio page)",
          "Driving License",
          "Voter ID",
          "Documents must be clear, unblurred, and fully visible",
          "File size must be under 5MB (JPG, PNG, or PDF)",
        ],
        followUps: ["how do i complete kyc", "my kyc was rejected. what do i do", "is my aadhaar number stored on ethertrack"],
        tags: ["kyc"],
      },
      {
        id: "kyc-rejected",
        question: "My KYC was rejected. What do I do?",
        keywords: ["kyc rejected", "kyc failed", "kyc declined", "kyc not approved", "resubmit kyc", "kyc issue", "kyc rejection"],
        answer: "Don't worry — KYC rejections are usually fixable. You'll receive an email with the reason. Common causes and fixes:",
        steps: [
          "Blurry or cropped photo → retake with better lighting",
          "Name mismatch → ensure your name matches exactly as on the ID",
          "Expired document → use a valid, non-expired ID",
          "Wrong document type → re-read accepted documents list",
          "Go back to the KYC form and resubmit with corrected documents",
          "If rejected again, raise a support ticket with your rejection reason",
        ],
        followUps: ["what documents are accepted for kyc", "how long does kyc approval take"],
        tags: ["kyc", "error", "blocked"],
        escalate: true,
      },
      {
        id: "kyc-time",
        question: "How long does KYC approval take?",
        keywords: ["kyc time", "kyc approval time", "how long kyc", "kyc pending", "kyc status", "waiting for kyc", "kyc duration"],
        answer: "KYC is typically reviewed within 1–2 business days. You'll receive an email once approved. If it's been more than 2 business days, raise a support ticket.",
        followUps: ["my kyc was rejected. what do i do", "the kyc banner is showing even though i completed kyc"],
        tags: ["kyc"],
      },
      {
        id: "kyc-expiry",
        question: "Does KYC expire?",
        keywords: ["kyc expire", "kyc expiry", "kyc renewal", "kyc valid", "kyc warning", "kyc expired"],
        answer: "Yes, KYC does expire. The platform shows a KYC expiry warning when you're approaching expiry — renew promptly to avoid trading suspension. You'll see the warning banner on your dashboard.",
        followUps: ["how do i complete kyc", "what happens if my subscription expires"],
        tags: ["kyc"],
      },
      {
        id: "kyc-aadhaar-privacy",
        question: "Is my Aadhaar number stored on EtherTrack?",
        keywords: ["aadhaar stored", "id number privacy", "data privacy", "kyc privacy", "id stored", "secure", "aadhaar safe", "kyc data"],
        answer: "No. Your actual ID number is never stored. Only a one-way cryptographic hash is recorded for duplicate prevention. Your document is stored on IPFS and accessible only by the compliance team. EtherTrack complies with DPDP Act 2023, IT Act 2000 S43A, and UIDAI guidelines.",
        followUps: ["what is ipfs", "how do i complete kyc"],
        tags: ["kyc"],
      },
    ],
  },

  // ── MODULE 3: Dashboard ───────────────────────────────────────────────────
  {
    id: "dashboard",
    icon: "🏠",
    label: "Dashboard",
    subtopics: [
      {
        id: "dashboard-overview",
        question: "What can I see on the Dashboard?",
        keywords: ["dashboard", "home screen", "main page", "overview", "what is on dashboard", "home page", "dashboard features"],
        answer: "The Dashboard is your EtherTrack home screen. Here's everything on it:",
        steps: [
          "Live Ticker — scrolling strip of all active listings with prices. Click any to go to the Market.",
          "Four Summary Cards — Portfolio Value (INR), INR Wallet balance, ETH Wallet, and Platform Trades.",
          "Live Market Panel — up to 4 active listings. Click VIEW ALL LISTINGS for the full market.",
          "Quick Actions Grid — Buy Credits, Portfolio, Log Emissions, Trade History, Retire Credits / KYC Verify, Settings.",
          "Emission Offset Progress Arc — semicircular gauge showing net-zero progress: MY EMITTED, MY RETIRED, NET.",
          "Portfolio Breakdown — credits by project with progress bars.",
          "Network Status Panel — live status of blockchain, smart contract, backend API, and ETH/INR rate.",
          "Carbon Market News — curated headlines.",
          "Recent Trades — your last few trades.",
        ],
        followUps: ["what do the dashboard stat cards mean", "the refresh data button is greyed out. why", "the kyc banner is showing even though i completed kyc"],
        tags: ["dashboard"],
      },
      {
        id: "dashboard-stats",
        question: "What do the dashboard stat cards mean?",
        keywords: ["stat cards", "portfolio value", "inr wallet card", "eth wallet card", "platform trades", "dashboard cards", "summary cards"],
        answer: "The four summary cards at the top show key account info:",
        steps: [
          "Portfolio Value (green) — total value of your carbon credits in INR, vintage-adjusted. Shows tCO2 held and P&L.",
          "INR Wallet (light green) — your EtherTrack rupee balance. Deposit via UPI/NEFT/Net Banking.",
          "ETH Wallet (blue) — your MetaMask ETH balance with live INR equivalent. Only appears if MetaMask is connected.",
          "Platform Trades (purple) — total on-chain buy and sell trades on the whole platform with total volume in INR.",
        ],
        followUps: ["why is my eth balance showing a loading shimmer", "how do i deposit inr / add funds"],
        tags: ["dashboard"],
      },
      {
        id: "dashboard-faq",
        question: "Why is my ETH balance showing a loading shimmer?",
        keywords: ["eth shimmer", "eth balance loading", "inr equivalent not showing", "dashboard loading", "metamask balance not showing", "eth not loading"],
        answer: "The shimmer means the live ETH/INR exchange rate is still loading from the backend. Once fetched, your INR equivalent appears. If it never loads, check MetaMask is connected and click the 'Refresh Data' button.",
        followUps: ["the refresh data button is greyed out. why", "how do i connect my wallet"],
        tags: ["dashboard", "wallet"],
      },
      {
        id: "dashboard-refresh",
        question: "The Refresh Data button is greyed out. Why?",
        keywords: ["refresh button greyed", "refresh cooldown", "can't refresh", "dashboard not refreshing", "refresh timer", "refresh disabled"],
        answer: "The Refresh Data button has a cooldown timer to prevent overloading data. Wait for the countdown to reach 0, then click again. This is by design to keep data fetching efficient.",
        followUps: ["what can i see on the dashboard"],
        tags: ["dashboard"],
      },
      {
        id: "dashboard-kyc-banner",
        question: "The KYC banner is showing even though I completed KYC",
        keywords: ["kyc banner still showing", "kyc verified but banner", "kyc approved but locked", "kyc completed but showing warning", "kyc banner not going away"],
        answer: "Try refreshing the page first. If the banner still shows, your KYC may still be under admin review (takes 1–2 business days). Once the admin approves it, the banner disappears and all locked features unlock.",
        followUps: ["how long does kyc approval take", "what is kyc and why do i need it"],
        tags: ["dashboard", "kyc"],
      },
    ],
  },

  // ── MODULE 4: Wallet & Blockchain ─────────────────────────────────────────
  {
    id: "wallet",
    icon: "👛",
    label: "Wallet & Blockchain",
    subtopics: [
      {
        id: "connect-wallet",
        question: "How do I connect my wallet?",
        keywords: ["connect wallet", "wallet connect", "metamask", "web3", "bind wallet", "link wallet", "setup wallet", "add wallet"],
        answer: "Here's how to connect your Web3 wallet to EtherTrack:",
        steps: [
          "Make sure MetaMask is installed in your browser",
          "Click the MetaMask pill in the header (top right), or go to Settings → Wallet Bind",
          "Click 'Connect Wallet' — MetaMask pops up",
          "Approve the connection request in MetaMask",
          "EtherTrack signs a challenge message to link your wallet — this is a free off-chain signature, no ETH is spent",
          "Your wallet address is now linked. The header pill shows your address.",
        ],
        followUps: ["metamask is showing the wrong network", "i see a wallet mismatch warning", "my metamask shows 'not linked'. what does that mean"],
        tags: ["wallet"],
      },
      {
        id: "wallet-wrong-network",
        question: "MetaMask is showing the wrong network",
        keywords: ["wrong network", "metamask network", "sepolia", "network error", "switch network", "ethereum network", "mainnet vs testnet"],
        answer: "EtherTrack uses the Ethereum Sepolia testnet. In MetaMask, switch to 'Sepolia Test Network'. If Sepolia is not visible, go to MetaMask Settings → Advanced → enable 'Show test networks'.",
        followUps: ["how do i connect my wallet", "my transaction failed. what do i do"],
        tags: ["wallet", "error"],
      },
      {
        id: "wallet-not-linked",
        question: "My MetaMask shows 'Not Linked'. What does that mean?",
        keywords: ["not linked", "wallet not linked", "account link", "wallet unlinked", "link wallet to account", "metamask not linked"],
        answer: "It means your wallet address isn't bound to your EtherTrack account yet. Click 'Connect' in the header wallet dropdown — EtherTrack will sign a challenge message (free, no gas) to link it automatically.",
        followUps: ["how do i connect my wallet", "i see a wallet mismatch warning"],
        tags: ["wallet"],
      },
      {
        id: "wallet-mismatch",
        question: "I see a wallet mismatch warning",
        keywords: ["wallet mismatch", "wrong wallet", "wallet error", "mismatch banner", "different wallet", "wallet not matching", "mismatch warning"],
        answer: "A wallet mismatch means the active wallet in your browser differs from the one linked to your account. Fix it:",
        steps: [
          "Open MetaMask and check which account is currently active",
          "Switch to the wallet address linked to your EtherTrack account",
          "If you've lost access to that wallet, go to Settings → Wallet Bind to update it",
          "Sign the new verification message to link the new wallet",
          "The mismatch banner disappears once wallets are in sync",
        ],
        followUps: ["how do i connect my wallet", "my transaction failed. what do i do"],
        tags: ["wallet", "error"],
      },
      {
        id: "transactions",
        question: "How do I view my transactions?",
        keywords: ["view transactions", "transaction history", "tx history", "my transactions", "on-chain history", "past trades", "check transaction"],
        answer: "All your on-chain activity is tracked in one place:",
        steps: [
          "Click 'Transaction Status' in the sidebar",
          "You'll see all transactions — pending, confirmed, and failed",
          "Click any transaction to see its on-chain details and block explorer link",
          "Use filters to view by type — buy, sell, retire, transfer",
        ],
        followUps: ["my transaction failed. what do i do", "a trade shows 'pending'. does that mean it failed"],
        tags: ["wallet"],
      },
      {
        id: "transaction-failed",
        question: "My transaction failed. What do I do?",
        keywords: ["transaction failed", "tx failed", "transaction error", "transaction not going through", "failed transaction", "transaction stuck", "tx error"],
        answer: "Transaction failures are usually gas issues or network congestion. Here's what to check:",
        steps: [
          "Check if you have enough ETH in your wallet for gas fees",
          "Go to Transaction Status and check the exact error message",
          "If it shows 'Insufficient funds' — top up your ETH balance",
          "If it shows 'Nonce error' — reset your MetaMask account (Settings → Advanced → Reset Account)",
          "If the network is congested, wait a few minutes and retry (Sepolia confirms in 15–60 seconds)",
          "If it keeps failing, raise a support ticket with the transaction hash",
        ],
        followUps: ["what are gas fees", "metamask is showing the wrong network"],
        tags: ["wallet", "error", "blocked"],
        escalate: true,
      },
    ],
  },

  // ── MODULE 5: INR Wallet & Payments ───────────────────────────────────────
  {
    id: "inr-wallet",
    icon: "💰",
    label: "INR Wallet & Payments",
    subtopics: [
      {
        id: "inr-wallet-overview",
        question: "What is the INR Wallet?",
        keywords: ["inr wallet", "rupee wallet", "wallet page", "wallet balance", "what is inr wallet", "financial hub", "rupee balance"],
        answer: "The INR Wallet is your EtherTrack financial hub. It lets you manage your rupee balance, deposit and withdraw funds, manage bank accounts, and handle subscriptions. Navigate to WALLET in the header. Requires KYC.",
        followUps: ["how do i deposit inr / add funds", "how do i withdraw inr", "how do i add or manage bank accounts"],
        tags: ["inr"],
      },
      {
        id: "deposit-inr",
        question: "How do I deposit INR / add funds?",
        keywords: ["deposit", "add funds", "deposit inr", "top up", "add money", "upi", "net banking", "razorpay", "fund wallet", "add inr", "load wallet"],
        answer: "Deposits are processed securely via Razorpay. Here's how:",
        steps: [
          "Go to the Wallet page and click 'Deposit'",
          "Enter the amount (min ₹100, max ₹1,00,000). Use quick-select: ₹500, ₹1000, ₹2000, ₹5000, ₹10000",
          "Click Next and choose: UPI, Scan QR, or Net Banking",
          "Click 'Pay Now' — Razorpay checkout opens. Do NOT close the window while processing.",
          "On success, you'll see 'FUNDS ADDED!' with reference number and GST invoice number (also emailed)",
          "Click Done — your balance updates immediately",
        ],
        followUps: ["my deposit went through on razorpay but my balance didn't update", "what is tds and why is it charged on my withdrawal"],
        tags: ["inr", "billing"],
      },
      {
        id: "deposit-not-updated",
        question: "My deposit went through on Razorpay but my balance didn't update",
        keywords: ["deposit not updated", "balance not showing", "payment done but no balance", "razorpay success but no funds", "balance not reflecting"],
        answer: "Refresh the page first. If the balance still hasn't updated after 5 minutes, contact support@ethertrack.in with your Razorpay Payment ID — we'll sort it out immediately.",
        tags: ["inr", "error"],
        escalate: true,
      },
      {
        id: "withdraw-inr",
        question: "How do I withdraw INR?",
        keywords: ["withdraw", "withdrawal", "withdraw inr", "withdraw money", "send to bank", "bank transfer", "payout", "cash out"],
        answer: "Here's how to withdraw funds to your bank account:",
        steps: [
          "Go to the Wallet page and click 'Withdraw'",
          "Enter the amount (min ₹100, max your available balance)",
          "If the amount exceeds ₹10,000, a TDS breakdown is shown (1% TDS under Section 194S)",
          "Click Next and select a saved bank account, or enter Account Holder Name, Account Number, and IFSC Code",
          "IFSC must be in the format XXXX0XXXXXX (4 letters, 0, 6 alphanumeric)",
          "Click Confirm — processed via Razorpay Payouts",
          "You'll see 'WITHDRAWAL INITIATED!' with reference, TDS deducted, and net amount",
          "Funds reach your bank in 1–2 business days via NEFT/IMPS",
        ],
        followUps: ["what is tds and why is it charged on my withdrawal", "how do i add or manage bank accounts"],
        tags: ["inr"],
      },
      {
        id: "tds-explained",
        question: "What is TDS and why is it charged on my withdrawal?",
        keywords: ["tds", "tax deducted", "194s", "tds on withdrawal", "crypto tax", "tax on withdrawal", "tds deduction", "tax"],
        answer: "TDS (Tax Deducted at Source) applies to crypto/VDA transfers under Section 194S of the Indian Income Tax Act.",
        steps: [
          "Applies to withdrawals above ₹10,000",
          "Rate: 1% of the withdrawal amount",
          "Example: Withdraw ₹50,000 — TDS = ₹500 — You receive ₹49,500",
          "EtherTrack deducts this and issues a TDS Certificate",
          "You can claim the TDS credit when filing your ITR",
        ],
        followUps: ["how do i withdraw inr", "what is section 194s"],
        tags: ["inr", "billing"],
      },
      {
        id: "bank-accounts",
        question: "How do I add or manage bank accounts?",
        keywords: ["bank account", "add bank", "save bank", "bank details", "ifsc", "account number", "default bank", "manage bank"],
        answer: "Manage saved bank accounts under Wallet → Bank Accounts tab:",
        steps: [
          "Go to Wallet → Bank Accounts tab",
          "Click 'Add Account' and enter: Account Holder Name, Bank Name, Account Number, IFSC Code",
          "Click 'Save Account' — account number is masked (last 4 digits only) for security",
          "Click 'Set Default' to make it the default for withdrawals",
          "Click 'Delete' to remove a saved account (requires confirmation)",
        ],
        followUps: ["how do i withdraw inr", "what is tds and why is it charged on my withdrawal"],
        tags: ["inr"],
      },
      {
        id: "inr-balance-locked",
        question: "My INR balance shows a 'locked' amount. Why?",
        keywords: ["locked balance", "funds locked", "balance on hold", "escrow inr", "pending trade balance", "locked funds"],
        answer: "A locked amount means funds are held in a pending trade — reserved for an active order. Once the trade completes or is cancelled, the funds are released back to your available balance.",
        followUps: ["how do i cancel a bid? where does my eth go when a bid expires", "what are the different order types"],
        tags: ["inr"],
      },
    ],
  },

  // ── MODULE 6: Carbon Credits ──────────────────────────────────────────────
  {
    id: "carbon-credits",
    icon: "🌿",
    label: "Carbon Credits",
    subtopics: [
      {
        id: "buy-credits",
        question: "How do I buy carbon credits?",
        keywords: ["buy credits", "purchase credits", "buy carbon", "marketplace", "get credits", "acquire credits", "how to buy"],
        answer: "Buying carbon credits is fully on-chain. Here's how:",
        steps: [
          "Make sure your KYC is approved and wallet is connected",
          "Go to 'Market' from the header",
          "Browse listings — filter by project type, vintage year, price, registry standard",
          "Select a listing and enter the quantity",
          "Choose payment: INR Wallet (instant, no MetaMask needed) or MetaMask (ETH, on-chain)",
          "Review: subtotal + vintage adjustment + platform fee (0.5%) = total",
          "Click 'Buy' and confirm — INR: instant; ETH: confirm in MetaMask",
          "Credits appear in your Portfolio (Bought tab) once confirmed",
        ],
        followUps: ["what are the different order types", "what payment methods can i use to buy credits", "how do i check my portfolio"],
        tags: [],
      },
      {
        id: "sell-credits",
        question: "How do I sell or list carbon credits?",
        keywords: ["sell credits", "list credits", "sell carbon", "create listing", "put up for sale", "marketplace listing", "list for sale"],
        answer: "You need a Starter plan or above to list credits. Here's how:",
        steps: [
          "Go to Portfolio (Held tab) and select the credits you want to sell",
          "Click 'List' on the credit card",
          "Set quantity using the slider (1 to max held)",
          "Enter your Asking Price per credit in INR — reference price is shown as a guide",
          "Review: listing value in INR and equivalent ETH price",
          "If listing compliance credits (CCC), note the CCTS price band warning (₹600–₹1200)",
          "Click 'List On Marketplace' — goes live immediately via MetaMask",
        ],
        followUps: ["what is the retire button is greyed out. why", "how do i bulk list or retire credits"],
        tags: ["billing"],
      },
      {
        id: "retire-credits",
        question: "How do I retire carbon credits?",
        keywords: ["retire credits", "retirement", "offset", "cancel credits", "burn credits", "neutralize", "how to retire"],
        answer: "Retiring credits permanently removes them from circulation. Admin role is required. Here's how:",
        steps: [
          "Go to Portfolio → Held tab and select credits to retire",
          "Click 'Retire' — set quantity with the slider",
          "Select Offset Scope: Scope 1, 2, or 3 — shown on certificate",
          "Optionally add Corporate Beneficiary: name, company, and GSTIN",
          "Select Purpose: Voluntary offset, Regulatory compliance, Net zero, or Supply chain",
          "Select Reporting Framework: GHG Protocol, CDP, SEBI BRSR, TCFD, or ISO 14064-3",
          "Click 'Retire' and confirm in MetaMask — this is IRREVERSIBLE (tokens burned on-chain)",
          "Retirement Certificate is generated automatically once confirmed",
        ],
        followUps: ["how do i get my retirement certificate", "the retire button is greyed out. why", "how do i bulk list or retire credits"],
        tags: [],
      },
      {
        id: "retire-greyed-out",
        question: "The Retire button is greyed out. Why?",
        keywords: ["retire greyed out", "cannot retire", "retire disabled", "no retire button", "retirement permission", "retire button not working"],
        answer: "Retirement requires Admin role in your organization. If you have Manager, Analyst, or Viewer role, you don't have retirement permissions. Contact your org admin to upgrade your role.",
        followUps: ["what are the different team roles", "how do i retire carbon credits"],
        tags: ["blocked"],
      },
      {
        id: "bulk-retire",
        question: "How do I bulk list or retire credits?",
        keywords: ["bulk retire", "bulk list", "multiple credits", "bulk actions", "select mode", "retire all", "list all"],
        answer: "Bulk actions let you list or retire up to 10 credits at once:",
        steps: [
          "Go to Portfolio → Held tab",
          "Click 'Select Mode' to enable bulk selection",
          "Click the checkbox area on each card to select (max 10 at a time)",
          "The bulk action bar appears at the bottom",
          "To bulk list: enter your INR price, click 'List All'",
          "To bulk retire: click 'Retire All' (Admin role required)",
          "A progress bar shows how many credits have been processed",
        ],
        followUps: ["how do i retire carbon credits", "how do i sell or list carbon credits"],
        tags: [],
      },
      {
        id: "certificate",
        question: "How do I get my retirement certificate?",
        keywords: ["certificate", "retirement certificate", "pdf certificate", "proof of retirement", "download certificate", "get certificate", "carbon certificate"],
        answer: "Your certificate is auto-generated after every retirement:",
        steps: [
          "Go to Portfolio → Retired tab",
          "Find your retirement record and click 'Certificate'",
          "The modal shows: Certificate ID, Token ID, QR Code, and public Verification URL",
          "Click 'Download PDF' — includes credit details, retirement date, on-chain tx hash, beneficiary, and reporting framework",
          "Click 'Verify' to open the public verification page (anyone can verify)",
          "Share the verification URL or QR code as proof",
        ],
        followUps: ["how do i retire carbon credits", "how do i submit / tokenize a new carbon credit"],
        tags: [],
      },
      {
        id: "tokenize-credit",
        question: "How do I submit / tokenize a new carbon credit?",
        keywords: ["tokenize", "submit credit", "add credit", "new credit", "mint credit", "register credit", "upload credit", "tokenize carbon"],
        answer: "Tokenizing submits your carbon credits for admin verification. KYC and Manager role or above required:",
        steps: [
          "Click 'TOKENIZE NEW CREDIT' in the Portfolio top bar",
          "Enter Project Name, Pincode (auto-fills Location/Country), Registry Standard, Project ID, Project Type, Project Developer, and Quantity in tCO2",
          "Enter Vintage Year (cannot be future) and Expiry Date (must be future)",
          "Enter Serial / Certificate Number from your registry",
          "Select Credit Type: Voluntary (VCU) or Compliance (CCC for India CCTS)",
          "Select SDG Co-Benefits (required for Gold Standard credits)",
          "Toggle CBAM Eligibility if applicable (EU Article 7)",
          "Upload Ownership Proof document (PDF, JPG, PNG — max 5MB) — pinned to IPFS permanently",
          "Click 'Submit For Verification' — admin review takes 1–2 business days",
        ],
        followUps: ["my credit shows 'minting' — what does that mean", "what are the different tabs in my portfolio"],
        tags: [],
      },
    ],
  },

  // ── MODULE 7: Carbon Credit Market ────────────────────────────────────────
  {
    id: "market",
    icon: "📈",
    label: "Carbon Credit Market",
    subtopics: [
      {
        id: "market-overview",
        question: "How does the Carbon Credit Market work?",
        keywords: ["market", "exchange", "marketplace", "how does market work", "trading", "buy sell market", "market page"],
        answer: "The Market page is EtherTrack's live carbon credit exchange. Browsing is open to all users — trading requires KYC.",
        steps: [
          "Market tab — full listings table with filters, sorting, watchlist, mini charts, and price sparklines",
          "Trade tab — order book, credit info, price history, and order form (Market / Limit / Bid types)",
          "Analytics tab — price chart for selected token and market overview stats",
          "AMM tab — Automated Market Maker for instant small swaps (≤100 credits) without a counterparty",
          "History tab — full on-chain trade history",
          "My Bids tab — your active buy bids with ETH locked in escrow. Cancel bids here.",
          "Alerts tab — set and manage price alerts",
        ],
        followUps: ["what are the different order types", "what is the amm and how do i use it", "how do i set up price alerts"],
        tags: ["market"],
      },
      {
        id: "market-order-types",
        question: "What are the different order types?",
        keywords: ["market order", "limit order", "bid", "order type", "how to trade", "buy order", "order types"],
        answer: "EtherTrack supports three order types in the Trade tab:",
        steps: [
          "Market Order — buy immediately at the current listing price. Choose quantity, select payment (INR Wallet or MetaMask), review fees, confirm.",
          "Limit Order — set a maximum price you're willing to pay. Executes only if a seller lists at or below your limit price.",
          "Bid (On-Chain Escrow) — place a buy bid at your desired price. ETH is locked in smart contract escrow. When a seller lists at your price, the trade auto-executes. Bids expire in 7, 14, or 30 days.",
        ],
        followUps: ["how do i cancel a bid? where does my eth go when a bid expires", "what payment methods can i use to buy credits"],
        tags: ["market"],
      },
      {
        id: "payment-methods-market",
        question: "What payment methods can I use to buy credits?",
        keywords: ["payment method", "inr payment", "eth payment", "metamask payment", "how to pay", "wallet payment", "credit payment"],
        answer: "EtherTrack supports two payment methods:",
        steps: [
          "INR Wallet — Instant settlement from your EtherTrack rupee balance. No MetaMask needed. Recommended.",
          "MetaMask (ETH) — On-chain Ethereum transaction. ETH converted at live rate. Visible on Etherscan. Requires MetaMask on Ethereum Sepolia.",
          "Platform fee: 0.5% on all buy trades and AMM swaps. AMM also charges 0.3% pool fee.",
          "If your INR balance shows 'SHORT', click 'Add Funds to Wallet' to deposit more.",
        ],
        followUps: ["how do i deposit inr / add funds", "how do i connect my wallet"],
        tags: ["market", "inr"],
      },
      {
        id: "amm-swaps",
        question: "What is the AMM and how do I use it?",
        keywords: ["amm", "automated market maker", "instant swap", "pool", "swap credits", "no counterparty", "amm swap"],
        answer: "The AMM lets you swap ETH for credits (or credits for ETH) instantly without a matching seller — for ≤100 credits.",
        steps: [
          "Go to Market → AMM tab",
          "Select a pool — each shows credit reserve, ETH reserve, current price, and ACTIVE/INACTIVE status",
          "ETH to Credits: enter ETH amount, see estimated credits output",
          "Credits to ETH: enter credit amount, see estimated ETH output",
          "Review Price Impact (shown in red if above 5%) and Min received (2% slippage protection)",
          "Pool fee: 0.3% deducted from input",
          "Confirm swap — MetaMask required",
        ],
        followUps: ["what is price impact", "what are the different order types"],
        tags: ["market", "wallet"],
      },
      {
        id: "price-alerts",
        question: "How do I set up price alerts?",
        keywords: ["price alert", "alerts", "price notification", "set alert", "watch price", "price above below", "alert me"],
        answer: "Set price alerts in Market → Alerts tab:",
        steps: [
          "Go to Market → Alerts tab",
          "Select the listed credit you want to watch",
          "Toggle whether to alert when price goes Below or Above your target",
          "Enter your target price in INR",
          "Click 'Set Alert' — appears in Active Alerts with status 'Watching'",
          "Important: Alerts only work while the Market page is open in your browser",
        ],
        followUps: ["how does the carbon credit market work"],
        tags: ["market"],
      },
      {
        id: "cancel-bid",
        question: "How do I cancel a bid? Where does my ETH go when a bid expires?",
        keywords: ["cancel bid", "bid expired", "eth refund bid", "my bids", "escrow refund", "bid expiry", "bid cancel"],
        answer: "Manage bids in Market → My Bids tab. When a bid expires, your ETH is automatically returned from smart contract escrow to your MetaMask wallet — no action needed from you.",
        followUps: ["what are the different order types", "my transaction failed. what do i do"],
        tags: ["market", "wallet"],
      },
      {
        id: "buy-button-shows-view",
        question: "The Buy button shows 'View' instead. Why can't I buy?",
        keywords: ["buy button shows view", "can't buy", "view instead of buy", "trading locked", "kyc required to trade", "cant trade"],
        answer: "Trading requires KYC verification. You can browse the market without KYC, but the Buy button shows 'View' until your KYC is approved. Go to /kyc (or click VERIFY NOW on the dashboard) to complete it.",
        followUps: ["how do i complete kyc", "how long does kyc approval take"],
        tags: ["market", "kyc", "blocked"],
      },
    ],
  },

  // ── MODULE 8: Portfolio ───────────────────────────────────────────────────
  {
    id: "portfolio",
    icon: "📂",
    label: "Portfolio",
    subtopics: [
      {
        id: "portfolio-overview",
        question: "What is the Portfolio page?",
        keywords: ["portfolio", "my credits", "portfolio page", "what is portfolio", "credit management", "portfolio overview"],
        answer: "The Portfolio is your command centre for all your carbon credits. Requires Starter plan or above AND KYC. It has three sections: Overview (credit cards + stats), Analytics (charts), and Audit Log.",
        followUps: ["what are the different tabs in my portfolio", "what analytics does the portfolio offer", "how do i submit / tokenize a new carbon credit"],
        tags: ["portfolio"],
      },
      {
        id: "portfolio-tabs",
        question: "What are the different tabs in my Portfolio?",
        keywords: ["portfolio tabs", "held tab", "listed tab", "bought tab", "retired tab", "pending tab", "rejected tab", "portfolio sections"],
        answer: "Your Portfolio has 7 tabs:",
        steps: [
          "All — every credit you own, bought, or have pending",
          "Held — approved credits not yet listed on the market",
          "Listed — credits currently listed for sale",
          "Bought — credits purchased from other sellers",
          "Retired — credits permanently burned on-chain. Shows retirement certificates.",
          "Pending — credits submitted for admin verification. Cannot be traded until approved.",
          "Rejected — credits whose submission was rejected by admin.",
        ],
        followUps: ["my credit shows 'minting' — what does that mean", "i submitted a credit but it's not showing in pending"],
        tags: ["portfolio"],
      },
      {
        id: "portfolio-credit-minting",
        question: "My credit shows 'Minting' — what does that mean?",
        keywords: ["minting", "credit minting", "nft minting", "credit not appearing", "credit pending mint", "minting status"],
        answer: "The credit has been approved by admin but not yet minted on-chain as an NFT. This happens automatically — refresh the page after a few minutes and it should move to the Held tab.",
        followUps: ["what are the different tabs in my portfolio", "how do i submit / tokenize a new carbon credit"],
        tags: ["portfolio"],
      },
      {
        id: "portfolio-not-in-pending",
        question: "I submitted a credit but it's not showing in Pending",
        keywords: ["credit not showing", "submission not appearing", "submitted but not in pending", "tokenize not showing", "credit missing"],
        answer: "It can take a moment to appear. Click the Refresh button at the top of the Portfolio page. If it still doesn't appear after a few minutes, contact support.",
        tags: ["portfolio", "error"],
        escalate: true,
      },
      {
        id: "portfolio-reference-price",
        question: "What is the Reference Price in my Portfolio?",
        keywords: ["reference price", "ref price", "price difference", "listing price vs ref price", "price calculation", "credit price"],
        answer: "The Reference Price is calculated from your project type, registry standard, and vintage depreciation — older vintages have a depreciation discount. It's a guide price, not the final listing price. You set your own listing price when you list for sale.",
        followUps: ["how do i sell or list carbon credits", "what is vintage depreciation"],
        tags: ["portfolio"],
      },
      {
        id: "portfolio-analytics",
        question: "What analytics does the Portfolio offer?",
        keywords: ["portfolio analytics", "charts", "portfolio charts", "registry breakdown", "vintage chart", "project type chart", "portfolio data"],
        answer: "Portfolio → Analytics tab shows visual breakdowns of your holdings:",
        steps: [
          "Unique Projects — count of distinct project IDs",
          "CCP Eligible % — credits eligible for ICVCM Core Carbon Principles",
          "Standards count — distinct registry standards",
          "By Registry Standard — donut chart (VCS, GS, CDM, ACR, BEE splits)",
          "By Vintage Year — bar chart of credits by vintage year",
          "By Project Type — horizontal bar chart of top 7 project types by volume",
          "Retirement Timeline — line chart of monthly retirement volume (available after 2+ retirements)",
        ],
        followUps: ["what is ccp eligible", "what is the portfolio page"],
        tags: ["portfolio"],
      },
    ],
  },

  // ── MODULE 9: Trading History ─────────────────────────────────────────────
  {
    id: "trading-history",
    icon: "📋",
    label: "Trading History",
    subtopics: [
      {
        id: "trading-history-overview",
        question: "How do I view my trading history?",
        keywords: ["trading history", "trade history", "past trades", "transaction history", "history page", "my trades", "trade records"],
        answer: "The Trading History page shows a complete record of all your buy and sell transactions. Navigate to HISTORY in the header.",
        steps: [
          "Summary cards: Total Volume, Total Bought, Total Sold, Total Trades",
          "Table columns: TXN ID, Project, Type (Buy/Sell), Size, Price, Total (INR), ETH, Status",
          "Status types: Confirmed (green), Pending (yellow), Failed (red), AMM (green)",
          "10 transactions per page — use Prev/Next or page numbers",
          "Search by TXN ID or project name",
          "Filter by Type (All/Buy/Sell) and Status (All/Confirmed/Pending/Failed/AMM Swap)",
          "Click 'Export CSV' to download all trades — exports full history regardless of filters",
        ],
        followUps: ["a trade shows 'pending'. does that mean it failed", "how do i download my trade history"],
        tags: [],
      },
      {
        id: "trade-pending",
        question: "A trade shows 'Pending'. Does that mean it failed?",
        keywords: ["pending trade", "trade pending", "transaction pending", "pending not confirming", "stuck pending", "trade not confirming"],
        answer: "Pending just means the transaction is still being confirmed on the blockchain — not that it failed. Wait a few minutes and refresh. If it stays Pending for over 10 minutes, check Etherscan with the tx hash.",
        followUps: ["my transaction failed. what do i do", "how do i view my transactions"],
        tags: ["error"],
      },
      {
        id: "price-column-dash",
        question: "My trade shows a dash in the Price column. Why?",
        keywords: ["price column dash", "no price shown", "dash in price", "price not stored", "missing price", "price missing trade"],
        answer: "Some older trades may not have a stored per-credit INR price. The Total (INR) column still shows the total trade amount — that's the important figure. INR values are the actual prices at trade time, not recalculated at the current rate.",
        tags: [],
      },
      {
        id: "export-csv",
        question: "How do I download my trade history?",
        keywords: ["export csv", "download trades", "csv export", "trade history download", "export history", "download csv"],
        answer: "Click 'Export CSV' at the top right of the transactions table. All trades are exported regardless of active filters — you always get the full history.",
        tags: [],
      },
    ],
  },

  // ── MODULE 10: Emissions Tracking ─────────────────────────────────────────
  {
    id: "emissions",
    icon: "📊",
    label: "Emissions Tracking",
    subtopics: [
      {
        id: "log-emissions",
        question: "How do I log my emissions?",
        keywords: ["log emissions", "add emission", "track emissions", "ghg", "scope 1", "scope 2", "scope 3", "co2", "carbon footprint", "emission entry", "emissions tracking"],
        answer: "Emissions tracking is available on Growth plan and above. Here's how to log:",
        steps: [
          "Go to 'Emission Tracking' from the sidebar",
          "Click 'Add Emission Entry'",
          "Select the Scope — Scope 1 (direct), Scope 2 (electricity), or Scope 3 (value chain)",
          "Choose the activity category (e.g. fuel combustion, business travel, purchased goods)",
          "Enter the quantity and unit (litres, kWh, km, tonnes, etc.)",
          "Add the date and any notes",
          "Click Save — added to your GHG inventory ledger",
        ],
        followUps: ["what is the difference between scope 1, 2, and 3", "what is the brsr report and how do i generate it"],
        tags: [],
      },
      {
        id: "scope-types",
        question: "What is the difference between Scope 1, 2, and 3?",
        keywords: ["scope 1", "scope 2", "scope 3", "difference", "what is scope", "emission scope", "ghg scope", "scope difference"],
        answer: "The three GHG emission scopes:",
        steps: [
          "Scope 1 — Direct emissions from sources you own/control (company vehicles, on-site fuel burning)",
          "Scope 2 — Indirect emissions from purchased electricity, heat, or steam",
          "Scope 3 — All other indirect emissions across your value chain (business travel, supply chain, product use)",
          "Most companies start with Scope 1 & 2, then add Scope 3 over time",
          "EtherTrack supports all three with GHG Protocol-aligned calculations",
        ],
        followUps: ["how do i log my emissions", "what is the brsr report and how do i generate it"],
        tags: [],
      },
      {
        id: "offset-percentage-zero",
        question: "I retired credits but my emission offset % is still 0",
        keywords: ["offset 0", "emission offset not updating", "retired but offset still zero", "offset percentage wrong", "offset zero"],
        answer: "The offset % calculates from your logged emissions in the Emission Tracking module. If you haven't logged any emissions yet, there's nothing to offset against. Log your emissions first — the percentage updates automatically.",
        followUps: ["how do i log my emissions", "what is the emission offset progress arc on the dashboard"],
        tags: [],
      },
      {
        id: "brsr",
        question: "What is the BRSR report and how do I generate it?",
        keywords: ["brsr", "brsr report", "business responsibility", "sustainability report", "esg report", "generate report", "compliance report", "brsr pdf"],
        answer: "BRSR is a mandatory ESG disclosure for listed Indian companies. EtherTrack auto-generates it (Corporate plan required):",
        steps: [
          "Make sure all your emissions data is logged for the reporting period",
          "Go to 'Reports' from the sidebar",
          "Select 'BRSR Report' and choose the financial year",
          "Review the auto-filled data — edit any fields if needed",
          "Click 'Generate PDF' to download your BRSR-compliant report",
        ],
        followUps: ["what is the difference between scope 1, 2, and 3", "what plans does ethertrack offer"],
        tags: [],
      },
    ],
  },

  // ── MODULE 11: Plans & Billing ────────────────────────────────────────────
  {
    id: "subscription",
    icon: "💳",
    label: "Plans & Billing",
    subtopics: [
      {
        id: "plans-overview",
        question: "What plans does EtherTrack offer?",
        keywords: ["plans", "pricing", "subscription", "tiers", "what plans", "free plan", "starter", "growth", "corporate", "how much", "plan cost"],
        answer: "EtherTrack has 4 plans:",
        steps: [
          "Free — Dashboard, Market (browse), Trading History, Wallet, Profile/Settings. 1 seat.",
          "Starter (₹1,000/mo) — Everything in Free + Portfolio, listing & selling credits, CSV export. 3 seats.",
          "Growth (₹10,000/mo) — Everything in Starter + Scope 1/2/3 emissions, GHG reports, analytics. 10 seats.",
          "Corporate (Contact Sales) — Everything in Growth + BRSR/CDP/TCFD, Compliance Dashboard, Team Management, audit trail, PAT/CCTS, multi-entity. Custom seats.",
        ],
        followUps: ["how do i upgrade my plan", "i upgraded but still see locked features"],
        tags: ["billing"],
      },
      {
        id: "upgrade-plan",
        question: "How do I upgrade my plan?",
        keywords: ["upgrade plan", "change plan", "switch plan", "upgrade subscription", "get starter", "get growth", "buy plan", "upgrade billing"],
        answer: "Upgrading takes just a minute:",
        steps: [
          "Go to Wallet → Subscription tab (or /billing from the upgrade modal)",
          "Select billing cycle: Monthly or Annual (save 17% with annual)",
          "Select payment method: INR Wallet (instant), Card/UPI/Net Banking (Razorpay), or MetaMask",
          "Click 'Renew' or 'Upgrade' and confirm payment",
          "Your new plan activates immediately — features sync in background every 5 minutes, or refresh immediately",
        ],
        followUps: ["i upgraded but still see locked features", "what plans does ethertrack offer"],
        tags: ["billing"],
      },
      {
        id: "plan-features-locked",
        question: "I upgraded but still see locked features",
        keywords: ["upgraded but locked", "plan not updating", "features still locked", "plan not activating", "upgrade not working", "plan not reflecting"],
        answer: "Refresh the page! Your plan syncs every 5 minutes in the background — a manual page refresh updates it immediately. If it still shows locked after refreshing, contact support.",
        tags: ["billing", "error"],
      },
      {
        id: "plan-expired",
        question: "What happens if my subscription expires?",
        keywords: ["plan expired", "subscription expired", "plan renewal", "features locked after expiry", "renewal date", "expired plan"],
        answer: "If your subscription expires, features above the Free tier are locked. Your data is completely safe — nothing is deleted. Renew from Wallet → Subscription tab. You'll see an expiry warning banner within 30 days, and a red urgent banner within 7 days.",
        followUps: ["how do i upgrade my plan", "i'm having a billing or payment issue"],
        tags: ["billing"],
      },
      {
        id: "billing-issues",
        question: "I'm having a billing or payment issue",
        keywords: ["billing issue", "payment failed", "payment not going through", "charged wrong", "refund", "invoice", "receipt", "billing error", "payment problem"],
        answer: "For billing issues:",
        steps: [
          "Go to Wallet → Subscription tab to check your plan and payment status",
          "If a payment failed, check if your card details are up to date",
          "Try a different payment method if your card is being declined",
          "For incorrect charges or refund requests, raise a support ticket immediately",
          "For invoices, go to Wallet → Transactions tab to download past invoices",
          "If your wallet subscription payment fails with 'Insufficient balance', deposit more funds first",
        ],
        followUps: ["how do i deposit inr / add funds", "how do i upgrade my plan"],
        tags: ["billing", "error"],
        escalate: true,
      },
    ],
  },

  // ── MODULE 12: Organization & Team ────────────────────────────────────────
  {
    id: "org",
    icon: "🏢",
    label: "Organization & Team",
    subtopics: [
      {
        id: "create-org",
        question: "How do I create an organization?",
        keywords: ["create org", "create organization", "new organization", "setup company", "register company", "org setup", "make org"],
        answer: "Complete KYC first, then:",
        steps: [
          "Go to 'Join or Create Organization' from the sidebar or dashboard prompt",
          "Click 'Create New Organization'",
          "Fill in your company name, type, industry, and registration number",
          "Upload your company registration document (GST certificate, MCA filing, etc.)",
          "Submit — reviewed and activated within 1–2 business days",
          "Once active, invite team members and start using org features",
        ],
        followUps: ["how do i invite team members", "how do i join an existing organization"],
        tags: ["account"],
      },
      {
        id: "invite-team",
        question: "How do I invite team members?",
        keywords: ["invite team", "add member", "team member", "invite user", "add user", "team management", "give access", "invite colleague"],
        answer: "Corporate plan required for Team Management. Here's how:",
        steps: [
          "Go to 'Team Management' from the sidebar",
          "Click 'Invite Member'",
          "Enter the email address of the person you want to invite",
          "Select their role — Admin, Manager, Analyst, or Viewer",
          "Click Send Invite — they receive an email with a join link",
          "Once they accept, they appear in your team list",
          "You can change roles or remove members anytime",
        ],
        followUps: ["what are the different team roles", "how do i join an existing organization"],
        tags: ["account"],
      },
      {
        id: "team-roles",
        question: "What are the different team roles?",
        keywords: ["team roles", "admin role", "manager role", "analyst role", "viewer role", "permissions", "role difference", "user roles"],
        answer: "EtherTrack has four team roles:",
        steps: [
          "Admin — Full access including retiring credits, managing team members, and all org settings",
          "Manager — Can tokenize and list credits, but cannot retire credits",
          "Analyst — Can view portfolio, emissions data, and reports. Cannot trade or list.",
          "Viewer — Read-only access to dashboard and reports",
        ],
        followUps: ["the retire button is greyed out. why", "how do i invite team members"],
        tags: ["account"],
      },
      {
        id: "join-org",
        question: "How do I join an existing organization?",
        keywords: ["join org", "join organization", "accept invite", "org invite", "join team", "invited to org", "accept org invite"],
        answer: "Joining is done through an invite link from the org admin:",
        steps: [
          "Ask your org admin to send you an invite from Team Management",
          "You'll receive an email with a 'Join Organization' link",
          "Click the link — if you don't have an EtherTrack account, you'll be prompted to sign up first",
          "After signing up / logging in, you're automatically added to the org",
          "Complete KYC if you haven't already to unlock all features",
        ],
        followUps: ["how do i create an organization", "what are the different team roles"],
        tags: ["account"],
      },
    ],
  },

  // ── MODULE 13: Glossary — Every Term in the App ───────────────────────────
  {
    id: "glossary",
    icon: "📖",
    label: "Glossary",
    subtopics: [
      {
        id: "glossary-carbon-credits",
        question: "What are carbon credits / tCO2e?",
        keywords: ["carbon credit", "what is carbon credit", "tco2", "tco2e", "carbon offset", "credit unit", "co2 equivalent"],
        answer: "A carbon credit represents 1 tonne of CO2 equivalent (tCO2e) that has been reduced, avoided, or removed from the atmosphere. On EtherTrack, each credit is tokenized as an NFT on the Ethereum blockchain, making it verifiable and tradeable.",
        followUps: ["what is vcs", "what is vintage year", "how do i buy carbon credits"],
        tags: ["glossary"],
      },
      {
        id: "glossary-vcs",
        question: "What is VCS (Verified Carbon Standard)?",
        keywords: ["vcs", "verified carbon standard", "verra", "vcs standard", "vcs registry", "vcus"],
        answer: "VCS (Verified Carbon Standard), administered by Verra, is the world's most widely used voluntary greenhouse gas crediting program. Credits under VCS are called VCUs (Verified Carbon Units). EtherTrack supports VCS as one of its registry standards.",
        followUps: ["what is gold standard", "what is cdm", "what are carbon credits / tco2e"],
        tags: ["glossary"],
      },
      {
        id: "glossary-gs",
        question: "What is Gold Standard (GS)?",
        keywords: ["gold standard", "gs standard", "gs registry", "gold standard carbon"],
        answer: "Gold Standard is a premium carbon credit certification that ensures credits also deliver measurable sustainable development goals (SDGs) beyond carbon reduction. GS credits typically command a price premium. SDG Co-Benefits are required when tokenizing GS credits on EtherTrack.",
        followUps: ["what is vcs", "what are sdg co-benefits", "what are carbon credits / tco2e"],
        tags: ["glossary"],
      },
      {
        id: "glossary-cdm",
        question: "What is CDM (Clean Development Mechanism)?",
        keywords: ["cdm", "clean development mechanism", "cdm credits", "unfccc cdm"],
        answer: "CDM (Clean Development Mechanism) is a UN-backed carbon crediting standard under the Kyoto Protocol, administered by the UNFCCC. CDM credits (CERs) are widely accepted for compliance use. EtherTrack supports CDM as a registry standard.",
        followUps: ["what is vcs", "what is gold standard", "what is ccts"],
        tags: ["glossary"],
      },
      {
        id: "glossary-ccts",
        question: "What is CCTS (Carbon Credit Trading Scheme)?",
        keywords: ["ccts", "carbon credit trading scheme", "india ccts", "compliance credits", "ccc", "compliance carbon credits", "india carbon market"],
        answer: "CCTS is India's mandatory Carbon Credit Trading Scheme, administered by BEE (Bureau of Energy Efficiency) under the Ministry of Power. It operates an Emission Trading Scheme (ETS) and an Offset Mechanism. On EtherTrack, CCTS-compliant credits are called CCCs (Compliance Carbon Credits) and have a regulated price band of ₹600–₹1200 per credit.",
        followUps: ["what is pat scheme", "what is bee", "what are carbon credits / tco2e"],
        tags: ["glossary"],
      },
      {
        id: "glossary-pat",
        question: "What is the PAT Scheme?",
        keywords: ["pat scheme", "perform achieve trade", "pat", "energy efficiency", "pat credits", "pat india"],
        answer: "PAT (Perform, Achieve and Trade) is India's market-based energy efficiency mechanism by BEE. Industries that over-achieve their energy efficiency targets earn Energy Saving Certificates (ESCerts) that can be traded. EtherTrack's PAT module tracks and manages ESCerts for designated consumers (DCs).",
        followUps: ["what is ccts", "what is bee", "what is brsr report"],
        tags: ["glossary"],
      },
      {
        id: "glossary-bee",
        question: "What is BEE?",
        keywords: ["bee", "bureau of energy efficiency", "what is bee", "bee india"],
        answer: "BEE stands for Bureau of Energy Efficiency, a statutory body under India's Ministry of Power. BEE administers India's energy conservation programs including the PAT Scheme and the CCTS Carbon Market.",
        followUps: ["what is pat scheme", "what is ccts"],
        tags: ["glossary"],
      },
      {
        id: "glossary-ipfs",
        question: "What is IPFS?",
        keywords: ["ipfs", "what is ipfs", "interplanetary file system", "ipfs storage", "decentralized storage"],
        answer: "IPFS (InterPlanetary File System) is a decentralized, distributed file storage protocol. EtherTrack uses IPFS to permanently store KYC documents and carbon credit ownership proof — making them tamper-proof and accessible via a content hash, not a central server. This ensures your documents can't be altered or deleted.",
        followUps: ["is my aadhaar number stored on ethertrack", "how do i submit / tokenize a new carbon credit"],
        tags: ["glossary"],
      },
      {
        id: "glossary-amm",
        question: "What is an AMM (Automated Market Maker)?",
        keywords: ["amm", "automated market maker", "what is amm", "liquidity pool", "constant product", "pool"],
        answer: "An AMM (Automated Market Maker) is a type of decentralized exchange that uses a liquidity pool and a mathematical formula (x*y=k, constant product) to price assets — instead of matching individual buyers and sellers. On EtherTrack, the AMM lets you swap ETH for carbon credits (or vice versa) instantly for ≤100 credits, with a 0.3% pool fee.",
        followUps: ["what is the amm and how do i use it", "what is price impact"],
        tags: ["glossary"],
      },
      {
        id: "glossary-price-impact",
        question: "What is price impact?",
        keywords: ["price impact", "slippage", "what is price impact", "high price impact", "price impact warning"],
        answer: "Price impact is the difference between the expected price and the actual execution price of a trade, caused by the size of your order relative to the available liquidity in the pool. A high price impact (shown in red on EtherTrack when above 5%) means your trade will significantly shift the pool's price. EtherTrack protects you with 2% slippage tolerance — if the price shifts more than 2% during execution, the trade reverts.",
        followUps: ["what is the amm and how do i use it", "what is slippage"],
        tags: ["glossary"],
      },
      {
        id: "glossary-vintage",
        question: "What is vintage year / vintage depreciation?",
        keywords: ["vintage year", "vintage", "vintage depreciation", "what is vintage", "credit age", "older credits"],
        answer: "Vintage year is the year in which the emissions reduction represented by a carbon credit took place. Older vintage credits (e.g. from 2010) trade at a discount compared to recent vintages (e.g. 2023) because buyers prefer fresher impact. EtherTrack applies vintage depreciation automatically when calculating the Reference Price for your credits.",
        followUps: ["what is the reference price in my portfolio", "what are carbon credits / tco2e"],
        tags: ["glossary"],
      },
      {
        id: "glossary-ghg",
        question: "What is GHG Protocol?",
        keywords: ["ghg protocol", "greenhouse gas protocol", "ghg", "what is ghg", "ghg standard"],
        answer: "The GHG (Greenhouse Gas) Protocol is the most widely used international accounting tool for understanding, quantifying, and managing greenhouse gas emissions. It defines Scope 1, 2, and 3 emission categories. EtherTrack's emissions tracking module is GHG Protocol-aligned, and generated reports follow its methodology.",
        followUps: ["what is the difference between scope 1, 2, and 3", "how do i log my emissions"],
        tags: ["glossary"],
      },
      {
        id: "glossary-brsr",
        question: "What is BRSR?",
        keywords: ["brsr", "business responsibility sustainability report", "what is brsr", "sebi brsr", "esg india"],
        answer: "BRSR (Business Responsibility and Sustainability Report) is a mandatory ESG disclosure framework for top listed Indian companies, mandated by SEBI. It covers environmental, social, and governance metrics including GHG emissions, energy consumption, water usage, and sustainability initiatives. EtherTrack auto-generates BRSR reports from your logged emissions data (Corporate plan).",
        followUps: ["what is the brsr report and how do i generate it", "what is ghg protocol"],
        tags: ["glossary"],
      },
      {
        id: "glossary-cbam",
        question: "What is CBAM?",
        keywords: ["cbam", "carbon border adjustment mechanism", "what is cbam", "eu cbam", "eu carbon border"],
        answer: "CBAM (Carbon Border Adjustment Mechanism) is an EU regulation (Article 7, effective 2026) that puts a carbon price on imports of carbon-intensive goods from countries with weaker climate policies. If you export goods to the EU, your carbon credits may need to be CBAM-eligible. When tokenizing a credit on EtherTrack, you can toggle 'CBAM Eligibility' if applicable.",
        followUps: ["how do i submit / tokenize a new carbon credit", "what is ccts"],
        tags: ["glossary"],
      },
      {
        id: "glossary-ccp",
        question: "What is CCP Eligible (Core Carbon Principles)?",
        keywords: ["ccp", "core carbon principles", "what is ccp", "icvcm", "ccp eligible", "integrity council"],
        answer: "CCP Eligible means a carbon credit meets the Core Carbon Principles set by the ICVCM (Integrity Council for the Voluntary Carbon Market). These are a set of threshold quality standards to ensure carbon credits represent real, additional, and permanent emissions reductions. Your Portfolio Analytics shows the % of your credits that are CCP eligible.",
        followUps: ["what analytics does the portfolio offer", "what is vcs"],
        tags: ["glossary"],
      },
      {
        id: "glossary-nft",
        question: "What does it mean that carbon credits are NFTs?",
        keywords: ["nft", "non fungible token", "what is nft", "credit nft", "token id", "erc721", "blockchain token"],
        answer: "On EtherTrack, each carbon credit is minted as an NFT (Non-Fungible Token) on the Ethereum Sepolia blockchain using the ERC-721 standard. This makes every credit uniquely identifiable, traceable, and tamper-proof. Each NFT has a Token ID — visible on your credit cards in the Portfolio — and can be verified on the blockchain at any time.",
        followUps: ["my credit shows 'minting' — what does that mean", "what are carbon credits / tco2e"],
        tags: ["glossary"],
      },
      {
        id: "glossary-gas-fees",
        question: "What are gas fees?",
        keywords: ["gas fees", "gas", "ethereum gas", "what are gas fees", "transaction fee", "eth fee", "network fee"],
        answer: "Gas fees are small amounts of ETH paid to the Ethereum network to process on-chain transactions. On EtherTrack, gas is required for: buying credits with MetaMask, listing credits for sale, retiring credits, placing on-chain bids, and AMM swaps. You do NOT pay gas when: signing the wallet connection message, buying credits with INR Wallet, or any off-chain actions. Gas fees vary based on network congestion.",
        followUps: ["my transaction failed. what do i do", "what payment methods can i use to buy credits"],
        tags: ["glossary"],
      },
      {
        id: "glossary-escrow",
        question: "What is escrow in the context of bids?",
        keywords: ["escrow", "bid escrow", "eth escrow", "what is escrow", "locked eth bid", "smart contract escrow"],
        answer: "When you place a Bid order on EtherTrack, your ETH is locked in a smart contract escrow — meaning it's held securely in code, not by EtherTrack. The ETH is automatically released to the seller if your bid is matched, or returned to your wallet when the bid expires or is cancelled. No trust in EtherTrack is required — the smart contract enforces the rules.",
        followUps: ["how do i cancel a bid? where does my eth go when a bid expires", "what are the different order types"],
        tags: ["glossary"],
      },
      {
        id: "glossary-tds",
        question: "What is Section 194S / TDS on crypto?",
        keywords: ["section 194s", "194s", "tds crypto", "vda tax", "virtual digital asset tax", "tds india crypto"],
        answer: "Section 194S of the Indian Income Tax Act requires 1% TDS (Tax Deducted at Source) on payments for transfer of Virtual Digital Assets (VDAs), which includes carbon credits on blockchain. EtherTrack deducts this automatically on withdrawals above ₹10,000 and provides a TDS Certificate. You can claim this as a credit when filing your ITR.",
        followUps: ["what is tds and why is it charged on my withdrawal", "how do i withdraw inr"],
        tags: ["glossary"],
      },
      {
        id: "glossary-dpdp",
        question: "What is the DPDP Act?",
        keywords: ["dpdp", "dpdp act", "data protection", "digital personal data", "what is dpdp", "india privacy law"],
        answer: "The DPDP Act (Digital Personal Data Protection Act) 2023 is India's comprehensive data privacy law. EtherTrack complies with the DPDP Act, IT Act 2000 Section 43A, and UIDAI guidelines. This means your personal data (including KYC information) is processed lawfully, stored securely, and never sold to third parties.",
        followUps: ["is my aadhaar number stored on ethertrack", "what is ipfs"],
        tags: ["glossary"],
      },
      {
        id: "glossary-sdg",
        question: "What are SDG Co-Benefits?",
        keywords: ["sdg", "sustainable development goals", "sdg co benefits", "what are sdg", "un goals", "sdg credits"],
        answer: "SDGs (Sustainable Development Goals) are 17 global goals set by the UN to address poverty, inequality, climate change, and more. SDG Co-Benefits on a carbon credit mean the project also contributes to specific SDGs beyond climate action — for example, a reforestation project might benefit SDG 15 (Life on Land) and SDG 13 (Climate Action). EtherTrack requires SDG Co-Benefits to be specified when tokenizing Gold Standard credits.",
        followUps: ["what is gold standard", "how do i submit / tokenize a new carbon credit"],
        tags: ["glossary"],
      },
      {
        id: "glossary-sepolia",
        question: "What is Ethereum Sepolia testnet?",
        keywords: ["sepolia", "testnet", "ethereum testnet", "what is sepolia", "test network", "sepolia ethereum"],
        answer: "Ethereum Sepolia is a public testnet (test network) for the Ethereum blockchain. EtherTrack currently runs on Sepolia, meaning all transactions use test ETH (no real money). This allows real-world testing of all blockchain features without financial risk. To use EtherTrack, switch MetaMask to 'Sepolia Test Network'.",
        followUps: ["metamask is showing the wrong network", "how do i connect my wallet"],
        tags: ["glossary"],
      },
    ],
  },

  // ── MODULE 14: FAQ & Edge Cases ───────────────────────────────────────────
  {
    id: "faq-edge-cases",
    icon: "🆘",
    label: "FAQ & Edge Cases",
    subtopics: [
      // ── FAQ Pairs from real user questions ──
      {
        id: "faq-portfolio-value-zero",
        question: "My Portfolio Value shows ₹0 even though I have credits",
        keywords: ["portfolio value zero", "portfolio value 0", "portfolio showing zero", "credits but no value", "value not showing"],
        answer: "Portfolio Value is calculated from listed prices on the Marketplace. If none of your credits have an active matching listing, the system may show ₹0 as reference prices haven't loaded yet. Try refreshing the page. If it persists, check the Portfolio → Analytics tab for a breakdown.",
        followUps: ["what do the dashboard stat cards mean", "what analytics does the portfolio offer"],
        tags: ["portfolio", "edge-case"],
      },
      {
        id: "faq-eth-rate-stale",
        question: "The ETH/INR rate looks outdated or wrong",
        keywords: ["eth rate stale", "eth rate wrong", "eth price wrong", "inr rate stale", "exchange rate wrong", "eth rate not updating"],
        answer: "EtherTrack fetches live ETH/INR rates from external price feeds. If the rate looks outdated, check the Network Status Panel at the bottom of the dashboard — it shows whether the price feed is live. Click 'Refresh Data' to force an update. If the feed shows offline, it's a temporary network issue — wait a few minutes.",
        followUps: ["the refresh data button is greyed out. why", "what can i see on the dashboard"],
        tags: ["dashboard", "edge-case"],
      },
      {
        id: "faq-cant-see-market",
        question: "I can't see any listings in the Market. Why?",
        keywords: ["no listings", "market empty", "no credits in market", "market not loading", "empty marketplace", "no results market"],
        answer: "If the Market appears empty: (1) Check your filters — you may have filters applied that hide all results. Click 'Clear Filters'. (2) There may genuinely be no active listings at the moment — listings are created by sellers in real time. (3) If the page itself isn't loading, check your internet connection and the Network Status Panel on the dashboard.",
        followUps: ["how does the carbon credit market work", "how do i buy carbon credits"],
        tags: ["market", "edge-case"],
      },
      {
        id: "faq-metamask-popup-blocked",
        question: "MetaMask popup is not appearing when I try to confirm a transaction",
        keywords: ["metamask popup", "metamask not opening", "metamask not appearing", "confirm transaction", "metamask blocked", "metamask stuck"],
        answer: "MetaMask popups can get blocked. Here's how to fix it:",
        steps: [
          "Click the MetaMask extension icon in your browser toolbar — the pending request is likely waiting there",
          "If the extension icon shows an orange dot, click it to see pending requests",
          "Check if your browser is blocking popups for this site — allow popups for ethertrack",
          "Try refreshing the page and initiating the transaction again",
          "If MetaMask is completely unresponsive, try locking and unlocking it (Settings → Lock MetaMask)",
        ],
        followUps: ["my transaction failed. what do i do", "how do i connect my wallet"],
        tags: ["wallet", "edge-case"],
      },
      {
        id: "faq-duplicate-kyc",
        question: "I get 'Duplicate KYC' or 'ID already used' error",
        keywords: ["duplicate kyc", "id already used", "kyc already exists", "aadhaar already registered", "pan already registered"],
        answer: "This means your ID document is already associated with another EtherTrack account. Each government ID can only be used for one account. If you think this is an error (e.g. someone else used your ID without permission), contact support@ethertrack.in immediately with your ID details.",
        tags: ["kyc", "error", "edge-case"],
        escalate: true,
      },
      {
        id: "faq-phone-otp-not-received",
        question: "I'm not receiving the phone OTP during KYC",
        keywords: ["phone otp not received", "sms not received", "kyc phone otp", "mobile otp missing", "sms otp kyc"],
        answer: "Here's what to try if you're not receiving the phone OTP during KYC Step 3:",
        steps: [
          "Make sure your number is a valid 10-digit Indian mobile starting with 6, 7, 8, or 9",
          "Check if DND (Do Not Disturb) is activated on your number — it may block SMS",
          "Wait 60 seconds before requesting a new OTP",
          "Try moving to an area with better mobile signal",
          "If you still can't receive it after 3 attempts, contact support@ethertrack.in",
        ],
        followUps: ["how do i complete kyc", "my kyc was rejected. what do i do"],
        tags: ["kyc", "error", "edge-case"],
        escalate: true,
      },
      {
        id: "faq-inr-withdrawal-failed",
        question: "My withdrawal was initiated but I haven't received the money",
        keywords: ["withdrawal not received", "money not received", "bank transfer not received", "withdrawal pending", "payout not arrived", "withdrawal failed"],
        answer: "Withdrawals typically arrive within 1–2 business days via NEFT/IMPS. Here's what to check:",
        steps: [
          "Confirm the Withdrawal was shown as 'INITIATED' in your Wallet history",
          "Check the bank account number is correct (verify in Wallet → Bank Accounts)",
          "Wait for 2 full business days (weekends and holidays don't count)",
          "If still not received after 2 business days, contact support@ethertrack.in with your withdrawal reference number and bank details",
        ],
        followUps: ["how do i withdraw inr", "how do i add or manage bank accounts"],
        tags: ["inr", "error", "edge-case"],
        escalate: true,
      },
      {
        id: "faq-listing-not-visible",
        question: "I listed my credits but they're not showing in the Market",
        keywords: ["listing not visible", "listed but not in market", "credits not showing market", "listing not appearing", "credits listed but not visible"],
        answer: "After listing, it may take a moment to appear. Refresh the Market page. If still not showing after a few minutes, check your Portfolio → Listed tab to confirm the listing was created. If the listing shows there but not in the Market, contact support.",
        followUps: ["how do i sell or list carbon credits", "what are the different tabs in my portfolio"],
        tags: ["market", "portfolio", "edge-case"],
      },
      {
        id: "faq-cost-basis-unavailable",
        question: "My Portfolio shows 'Cost basis unavailable'. What does this mean?",
        keywords: ["cost basis unavailable", "cost basis", "p&l not showing", "portfolio cost", "cost basis missing"],
        answer: "Cost basis is the original purchase price used to calculate your P&L (profit/loss). 'Cost basis unavailable' appears when your credits were tokenized directly (not bought through the Market), so there's no recorded purchase price. This is normal for credits you submitted yourself — P&L is only calculated for credits bought via the Marketplace.",
        followUps: ["what do the dashboard stat cards mean", "what analytics does the portfolio offer"],
        tags: ["portfolio", "edge-case"],
      },
      {
        id: "faq-watchlist",
        question: "How do I add a credit to my watchlist?",
        keywords: ["watchlist", "watch credit", "add to watchlist", "follow credit", "track credit", "favourite credit"],
        answer: "In the Market listings table, click the star (☆) icon on any listing to add it to your watchlist. The star turns gold (★) when active. Filter by 'Watchlist' using the toggle at the top of the Market table to see only your watched credits.",
        followUps: ["how does the carbon credit market work", "how do i set up price alerts"],
        tags: ["market"],
      },
      {
        id: "faq-verify-certificate",
        question: "How do I verify a retirement certificate?",
        keywords: ["verify certificate", "certificate verification", "check certificate", "is certificate real", "certificate valid", "verify retirement"],
        answer: "Anyone can verify a retirement certificate publicly — no login needed. Visit ethertrack.in/verify/[Certificate-ID] in any browser. The page shows the credit details, retirement date, on-chain transaction hash (verifiable on Etherscan), and beneficiary. You can also scan the QR code on the PDF certificate to open the verification page directly.",
        followUps: ["how do i get my retirement certificate", "how do i retire carbon credits"],
        tags: [],
      },
      {
        id: "faq-forgot-email",
        question: "I forgot which email I used to sign up",
        keywords: ["forgot email", "which email", "lost email", "don't know email", "email not working"],
        answer: "Try any email addresses you commonly use — the 'Incorrect email or password' error on the Login page will tell you if that email is not registered. If you signed up with Google or Facebook, try logging in with those buttons instead. If you still can't recover access, contact support@ethertrack.in with your name and any details about your account.",
        tags: ["account", "edge-case"],
        escalate: true,
      },
      {
        id: "faq-two-orgs",
        question: "Can I be in multiple organizations?",
        keywords: ["multiple orgs", "two organizations", "more than one org", "switch org", "org switch", "two accounts"],
        answer: "Currently, each EtherTrack account is associated with one organization at a time. If you need access to multiple organizations, you would need separate accounts with separate email addresses. Contact support if you have a specific multi-entity use case — Corporate plan includes multi-entity consolidation features.",
        followUps: ["how do i create an organization", "what plans does ethertrack offer"],
        tags: ["account", "edge-case"],
      },
      {
        id: "faq-report-bug",
        question: "I found a bug. How do I report it?",
        keywords: ["bug report", "report bug", "something broken", "app issue", "report problem", "found bug", "report error"],
        answer: "We appreciate bug reports! Please raise a support ticket with: (1) a description of what happened, (2) the page/feature where it occurred, (3) steps to reproduce it, and (4) a screenshot if possible. You can also email bugs@ethertrack.in directly.",
        tags: ["error"],
        escalate: true,
      },
      {
        id: "faq-data-export",
        question: "Can I export my emissions data or portfolio data?",
        keywords: ["export data", "download data", "export emissions", "portfolio export", "data download", "csv emissions"],
        answer: "Yes! Here's what you can export: (1) Trade History — click 'Export CSV' in Trading History (available on all plans). (2) Portfolio data — available on Starter plan and above via Portfolio → export options. (3) GHG / Emissions reports — available as PDF on Growth plan and above. (4) BRSR report PDF — Corporate plan only.",
        followUps: ["how do i download my trade history", "what plans does ethertrack offer"],
        tags: [],
      },
      {
        id: "faq-contact-support",
        question: "How do I contact EtherTrack support?",
        keywords: ["contact support", "support email", "email support", "help email", "reach support", "talk to team"],
        answer: "You can reach EtherTrack support in two ways:",
        steps: [
          "Raise a Support Ticket — use this chat widget (click '🎫 Raise a support ticket') for non-urgent queries",
          "Email directly — support@ethertrack.in for general queries, bugs@ethertrack.in for bug reports, sales@ethertrack.in for Corporate/enterprise enquiries",
          "Response time: within 24 hours on business days",
        ],
        tags: [],
        escalate: true,
      },
    ],
  },

]; // ← end of KNOWLEDGE_BASE

// ─────────────────────────────────────────────────────────────────────────────
// INTENT PATTERNS
// ─────────────────────────────────────────────────────────────────────────────
export const INTENT_PATTERNS = {
  frustration: ["not working","doesn't work","broken","bug","issue","problem","stuck","can't","cannot","failed","error","wrong","help me","urgent","asap","nothing works","doesn't load","not loading"],
  greeting:    ["hi","hello","hey","hii","good morning","good evening","howdy","sup","yo","hola","what's up","greetings"],
  thanks:      ["thank","thanks","thank you","thx","ty","appreciate","helpful","great","awesome","perfect","you're the best","that helped"],
  escalate:    ["human","agent","person","support","talk to someone","real person","escalate","ticket","raise ticket","contact team","email support"],
  confusion:   ["confused","don't understand","what does","what is","explain","what do you mean","unclear","not sure","can you clarify"],
};

// ─────────────────────────────────────────────────────────────────────────────
// BOT PERSONA
// ─────────────────────────────────────────────────────────────────────────────
export const BOT_PERSONA = {
  name:        "Ethi",
  tagline:     "EtherTrack Support Assistant",
  greeting:    "Hey! 👋 I'm Ethi, your EtherTrack support assistant. I know everything about the app — ask me anything or pick a topic below!",
  notFound:    "Hmm, I don't have a specific answer for that yet. Try rephrasing, or I can connect you with our support team.",
  escalateMsg: "It looks like you might need human help for this one. Want me to raise a support ticket?",
};